# Generated by Django 5.0.6 on 2024-07-11 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_region_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hydropost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meteostation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HydropostValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('I', models.FloatField(blank=True, null=True)),
                ('II', models.FloatField(blank=True, null=True)),
                ('III', models.FloatField(blank=True, null=True)),
                ('IV', models.FloatField(blank=True, null=True)),
                ('V', models.FloatField(blank=True, null=True)),
                ('VI', models.FloatField(blank=True, null=True)),
                ('VII', models.FloatField(blank=True, null=True)),
                ('VIII', models.FloatField(blank=True, null=True)),
                ('IX', models.FloatField(blank=True, null=True)),
                ('X', models.FloatField(blank=True, null=True)),
                ('XI', models.FloatField(blank=True, null=True)),
                ('XII', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hydropost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hydropost_values', to='hydrometeorological.hydropost')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hydropost_values', to='common.region')),
                ('mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hydropost_values', to='hydrometeorological.mode')),
            ],
        ),
        migrations.CreateModel(
            name='MeteostationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('I', models.FloatField(blank=True, null=True)),
                ('II', models.FloatField(blank=True, null=True)),
                ('III', models.FloatField(blank=True, null=True)),
                ('IV', models.FloatField(blank=True, null=True)),
                ('V', models.FloatField(blank=True, null=True)),
                ('VI', models.FloatField(blank=True, null=True)),
                ('VII', models.FloatField(blank=True, null=True)),
                ('VIII', models.FloatField(blank=True, null=True)),
                ('IX', models.FloatField(blank=True, null=True)),
                ('X', models.FloatField(blank=True, null=True)),
                ('XI', models.FloatField(blank=True, null=True)),
                ('XII', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meteostation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meteostation_values', to='hydrometeorological.meteostation')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meteostation_values', to='common.region')),
                ('parameter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meteostation_values', to='hydrometeorological.parameter')),
            ],
        ),
    ]
