# Generated by Django 5.0.6 on 2024-07-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydrometeorological', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='ObjectType',
        ),
    ]
