# Generated by Django 5.0.7 on 2024-07-29 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_district_options_alter_region_options'),
        ('hydrometeorological', '0002_rename_type_objecttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hydropost',
            options={'verbose_name': 'Gidropost', 'verbose_name_plural': 'Gidropostlar'},
        ),
        migrations.AlterModelOptions(
            name='hydropostvalue',
            options={'verbose_name': 'Gidrometriya', 'verbose_name_plural': 'Gidrometriya'},
        ),
        migrations.AlterModelOptions(
            name='meteostation',
            options={'verbose_name': 'Meteostansiya', 'verbose_name_plural': 'Meteostansiyalar'},
        ),
        migrations.AlterModelOptions(
            name='meteostationvalue',
            options={'verbose_name': 'Meteorologiya', 'verbose_name_plural': 'Meteorologiya'},
        ),
        migrations.AlterField(
            model_name='hydropostvalue',
            name='I',
            field=models.FloatField(blank=True, null=True, verbose_name='Yanvar'),
        ),
        migrations.AlterField(
            model_name='hydropostvalue',
            name='II',
            field=models.FloatField(blank=True, null=True, verbose_name='Fevral'),
        ),
        migrations.AlterField(
            model_name='hydropostvalue',
            name='III',
            field=models.FloatField(blank=True, null=True, verbose_name='Mart'),
        ),
        migrations.AlterField(
            model_name='hydropostvalue',
            name='IV',
            field=models.FloatField(blank=True, null=True, verbose_name='Aprel'),
        ),
        migrations.AlterField(
            model_name='hydropostvalue',
            name='IX',
            field=models.FloatField(blank=True, null=True, verbose_name='Sentyabr'),
        ),
        migrations.AlterField(
            model_name='hydropostvalue',
            name='V',
            field=models.FloatField(blank=True, null=True, verbose_name='May'),
        ),
        migrations.AlterField(
            model_name='hydropostvalue',
            name='VI',
            field=models.FloatField(blank=True, null=True, verbose_name='Iyun'),
        ),
        migrations.AlterField(
            model_name='hydropostvalue',
            name='VII',
            field=models.FloatField(blank=True, null=True, verbose_name='Iyul'),
        ),
        migrations.AlterField(
            model_name='hydropostvalue',
            name='VIII',
            field=models.FloatField(blank=True, null=True, verbose_name='Avgust'),
        ),
        migrations.AlterField(
            model_name='hydropostvalue',
            name='X',
            field=models.FloatField(blank=True, null=True, verbose_name='Oktyabr'),
        ),
        migrations.AlterField(
            model_name='hydropostvalue',
            name='XI',
            field=models.FloatField(blank=True, null=True, verbose_name='Noyabr'),
        ),
        migrations.AlterField(
            model_name='hydropostvalue',
            name='XII',
            field=models.FloatField(blank=True, null=True, verbose_name='Dekabr'),
        ),
        migrations.AlterField(
            model_name='hydropostvalue',
            name='hydropost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hydropost_values', to='hydrometeorological.hydropost', verbose_name='Gidropost nomi'),
        ),
        migrations.AlterField(
            model_name='hydropostvalue',
            name='mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hydropost_values', to='hydrometeorological.mode', verbose_name='Rejim turi'),
        ),
        migrations.AlterField(
            model_name='hydropostvalue',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hydropost_values', to='common.region', verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='hydropostvalue',
            name='year',
            field=models.IntegerField(verbose_name='Yil'),
        ),
        migrations.AlterField(
            model_name='meteostationvalue',
            name='I',
            field=models.FloatField(blank=True, null=True, verbose_name='Yanvar'),
        ),
        migrations.AlterField(
            model_name='meteostationvalue',
            name='II',
            field=models.FloatField(blank=True, null=True, verbose_name='Fevral'),
        ),
        migrations.AlterField(
            model_name='meteostationvalue',
            name='III',
            field=models.FloatField(blank=True, null=True, verbose_name='Mart'),
        ),
        migrations.AlterField(
            model_name='meteostationvalue',
            name='IV',
            field=models.FloatField(blank=True, null=True, verbose_name='Aprel'),
        ),
        migrations.AlterField(
            model_name='meteostationvalue',
            name='IX',
            field=models.FloatField(blank=True, null=True, verbose_name='Sentyabr'),
        ),
        migrations.AlterField(
            model_name='meteostationvalue',
            name='V',
            field=models.FloatField(blank=True, null=True, verbose_name='May'),
        ),
        migrations.AlterField(
            model_name='meteostationvalue',
            name='VI',
            field=models.FloatField(blank=True, null=True, verbose_name='Iyun'),
        ),
        migrations.AlterField(
            model_name='meteostationvalue',
            name='VII',
            field=models.FloatField(blank=True, null=True, verbose_name='Iyul'),
        ),
        migrations.AlterField(
            model_name='meteostationvalue',
            name='VIII',
            field=models.FloatField(blank=True, null=True, verbose_name='Avgust'),
        ),
        migrations.AlterField(
            model_name='meteostationvalue',
            name='X',
            field=models.FloatField(blank=True, null=True, verbose_name='Oktyabr'),
        ),
        migrations.AlterField(
            model_name='meteostationvalue',
            name='XI',
            field=models.FloatField(blank=True, null=True, verbose_name='Noyabr'),
        ),
        migrations.AlterField(
            model_name='meteostationvalue',
            name='XII',
            field=models.FloatField(blank=True, null=True, verbose_name='Dekabr'),
        ),
        migrations.AlterField(
            model_name='meteostationvalue',
            name='year',
            field=models.IntegerField(verbose_name='Yil'),
        ),
    ]
