# Generated by Django 5.0.6 on 2024-07-04 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrogeological', '0002_well_address_well_district_well_location_well_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wells', to='hydrogeological.organization'),
        ),
    ]
