# Generated by Django 5.0.6 on 2024-07-04 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_region_district'),
        ('hydrogeological', '0003_well_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wells', to='common.district'),
        ),
        migrations.AlterField(
            model_name='well',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wells', to='common.region'),
        ),
    ]
