# Generated by Django 5.0.7 on 2024-07-29 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_district_options_alter_region_options'),
        ('hydrogeological', '0005_waterlevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordinate',
            options={'verbose_name': 'Koordinat', 'verbose_name_plural': 'Koordinatlar'},
        ),
        migrations.AlterModelOptions(
            name='waterlevel',
            options={'verbose_name': 'Yerosti suvlari sathi', 'verbose_name_plural': 'Yerosti suvlari sathi'},
        ),
        migrations.AlterModelOptions(
            name='well',
            options={'verbose_name': "Kuzatuv-burg'u qudug'i", 'verbose_name_plural': "Kuzatuv-burg'u qudug'lari"},
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='I',
            field=models.FloatField(blank=True, null=True, verbose_name='Yanvar'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='II',
            field=models.FloatField(blank=True, null=True, verbose_name='Fevral'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='III',
            field=models.FloatField(blank=True, null=True, verbose_name='Mart'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='IV',
            field=models.FloatField(blank=True, null=True, verbose_name='Aprel'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='IX',
            field=models.FloatField(blank=True, null=True, verbose_name='Sentyabr'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='V',
            field=models.FloatField(blank=True, null=True, verbose_name='May'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='VI',
            field=models.FloatField(blank=True, null=True, verbose_name='Iyun'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='VII',
            field=models.FloatField(blank=True, null=True, verbose_name='Iyul'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='VIII',
            field=models.FloatField(blank=True, null=True, verbose_name='Avgust'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='X',
            field=models.FloatField(blank=True, null=True, verbose_name='Oktyabr'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='XI',
            field=models.FloatField(blank=True, null=True, verbose_name='Noyabr'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='XII',
            field=models.FloatField(blank=True, null=True, verbose_name='Dekabr'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_levels', to='hydrogeological.well', verbose_name="Kuzatuv qudug'i raqami"),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='year',
            field=models.IntegerField(verbose_name='Yil'),
        ),
        migrations.AlterField(
            model_name='well',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Mo'ljal"),
        ),
        migrations.AlterField(
            model_name='well',
            name='created_at',
            field=models.DateTimeField(verbose_name="To'ldirilgan sanasi"),
        ),
        migrations.AlterField(
            model_name='well',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wells', to='common.district', verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='well',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wells', to='common.location', verbose_name="Joylashuv o'rni"),
        ),
        migrations.AlterField(
            model_name='well',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wells', to='hydrogeological.organization', verbose_name='Tashkilot'),
        ),
        migrations.AlterField(
            model_name='well',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wells', to='common.region', verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='well',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wells', to='hydrogeological.station', verbose_name='Stansiya'),
        ),
        migrations.AlterField(
            model_name='well',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wells', to='hydrogeological.welltype', verbose_name="Qudug'ining turi"),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_number',
            field=models.IntegerField(verbose_name="Kuzatuv qudug'i raqami"),
        ),
    ]
