# Generated by Django 5.0.6 on 2024-07-10 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_region_district'),
        ('hydromelioratical', '0002_remove_waterlevel_object_remove_coordinate_object_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinate',
            name='well_object',
        ),
        migrations.RemoveField(
            model_name='waterlevel',
            name='well_object',
        ),
        migrations.RenameModel(
            old_name='WellObjectType',
            new_name='WellType',
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_number', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='melio_wells', to='common.district')),
                ('expedicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='melio_wells', to='hydromelioratical.expedicion')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objects', to='common.location')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='melio_wells', to='hydromelioratical.organization')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='melio_wells', to='common.region')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='melio_wells', to='hydromelioratical.welltype')),
            ],
        ),
        migrations.AddField(
            model_name='coordinate',
            name='well',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='hydromelioratical.well'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterlevel',
            name='well',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='water_levels', to='hydromelioratical.well'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WellObject',
        ),
    ]
