# Generated by Django 5.0.7 on 2024-07-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydromelioratical', '0003_remove_coordinate_well_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterlevel',
            name='I',
            field=models.FloatField(blank=True, null=True, verbose_name='Yanvar'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='II',
            field=models.FloatField(blank=True, null=True, verbose_name='Fevral'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='III',
            field=models.FloatField(blank=True, null=True, verbose_name='Mart'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='IV',
            field=models.FloatField(blank=True, null=True, verbose_name='Aprel'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='IX',
            field=models.FloatField(blank=True, null=True, verbose_name='Sentyabr'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='V',
            field=models.FloatField(blank=True, null=True, verbose_name='May'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='VI',
            field=models.FloatField(blank=True, null=True, verbose_name='Iyun'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='VII',
            field=models.FloatField(blank=True, null=True, verbose_name='Iyul'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='VIII',
            field=models.FloatField(blank=True, null=True, verbose_name='Avgust'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='X',
            field=models.FloatField(blank=True, null=True, verbose_name='Oktyabr'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='XI',
            field=models.FloatField(blank=True, null=True, verbose_name='Noyabr'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='XII',
            field=models.FloatField(blank=True, null=True, verbose_name='Dekabr'),
        ),
        migrations.AlterField(
            model_name='waterlevel',
            name='year',
            field=models.IntegerField(verbose_name='Yil'),
        ),
    ]
